name: Merge Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  R-CMD-Check:
    uses: ./.github/workflows/R-CMD-check.yaml
  test-coverage:
    uses:  ./.github/workflows/test-coverage.yaml
  pkgdown:
    uses:  ./.github/workflows/pkgdown.yaml
