name: PR-Workflow

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:


jobs:
  # Detect changes done in C# code base. If no change were done, skim "build-Csharp-binaries" workflow.
  changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      Csharp: ${{ steps.filter.outputs.Csharp }}
    steps:
    - uses: dorny/paths-filter@v3
      id: filter
      with:
        filters: |
          Csharp:
            - 'inst/lib/**'
            - 'shared/**'

  build-Csharp-binaries:
    needs: changes
    if: ${{ needs.changes.outputs.Csharp == 'true' }}
    uses: ./.github/workflows/build-c#.yaml
  R-CMD-Check:
    needs: build-Csharp-binaries
    uses: ./.github/workflows/R-CMD-check.yaml
  test-coverage:
    needs: [build-Csharp-binaries, R-CMD-Check]
    uses:  ./.github/workflows/test-coverage.yaml
  pkgdown:
    needs: [build-Csharp-binaries, R-CMD-Check]
    uses:  ./.github/workflows/pkgdown.yaml
